config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
  end

  def confirm
    @post = Post.new(post_params)
  end

  def create
    @post = Post.new(post_params)

    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "ポストしました！"
      else
        render :new
      end
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "編集が完了しました！"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "投稿を削除しました！"
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create"
      confirm_posts_path
    elsif action_name == "edit"
      post_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bluebird</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_pack_tag "application" %>
  </head>
  <div>
    <header>
      <p>つぶやきアプリ</p>
    </header>
  </div>

  <body>
    <%= yield %>
  </body>
  <div>
    <footer>
      <p>(c)copy right</p>
    </footer>
  </div>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url: choose_new_or_edit) do |form| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%= form.submit "投稿", class: "btn btn-primary" %>

<% end %>

<%= link_to "ホームに戻る", posts_path %>

app/views/posts/confirm.html.erb
<h3>以下の内容で送信しますか？</h3>

<%= form_with(model: @post, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>内容：<%= @post.content %></p>
  <%= form.submit "投稿"%>
  <%= form.submit "戻る", name: 'back' %>

<% end %>

app/views/posts/edit.html.erb
<h2>ポストを編集する</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h2>ホーム画面</h2>

<p><%= notice %></p>

<%= link_to '新しくポストする', new_post_path %>

<table>
  <% @posts.each do |post| %>
    <tr>
       <td><%= post.content %></td>
       <td><%= link_to '編集', edit_post_path(post.id) %></td>
       <td><%= link_to '削除', post_path(post.id), method: :delete ,data: { confirm: '本当に削除してよろしですか？'} %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h2>ポストする</h2>

<%= render 'form' %>